server:
  port: ${PORT:8081}

spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/relief-finder}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:postgres}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  output:
    ansi:
      enabled: ALWAYS
  http:
    log-request-details: true
  jackson:
    default-property-inclusion: NON_NULL
  devtools:
    remote:
      proxy:
        host: localhost
        port: 8888
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  level:
    org.springframework.web: TRACE

facebook-messenger:
  messaging-url: https://graph.facebook.com/v2.6/me/messages
  access-token: EAAFZBlJlGTq0BAL8pydMUwKA3xJZCILTFAf0lCTqAJJp2cqIl9ZCBnSKcZAMnU4NqEmgdbcvUiXZANEXOGPgm9qF4WjJDc5r2rLz4mZBBiAE5uHcCUkZA1RizfsQMppoCwtBoBnEKBPZA0Gh6dzyQNbh5T2PusufaGdT6UjZBfGbiSXziY3QmdI98RyAzPYZARZAKMZD
